// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Customers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Customers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		PhoneNumber("PhoneNumber"),
		Gender("Gender"),
		MaritalStatus("MaritalStatus"),
		Email("Email"),
		Password("Password"),
		AnnualSalary("AnnualSalary"),
		SalesOrderQuantity("SalesOrderQuantity");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Customers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customersMendixObject)
	{
		if (customersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, customersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customersMendixObject = customersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Customers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Customers(context, mendixObject);
	}

	public static myfirstmodule.proxies.Customers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Customers.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Customers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Customers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * Get value of Gender
	 * @param gender
	 */
	public final myfirstmodule.proxies.Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final myfirstmodule.proxies.Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(myfirstmodule.proxies.Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Gender gender)
	{
		if (gender != null) {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
		}
	}

	/**
	 * Get value of MaritalStatus
	 * @param maritalstatus
	 */
	public final myfirstmodule.proxies.MaritalStatus getMaritalStatus()
	{
		return getMaritalStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MaritalStatus
	 */
	public final myfirstmodule.proxies.MaritalStatus getMaritalStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MaritalStatus.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.MaritalStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MaritalStatus
	 * @param maritalstatus
	 */
	public final void setMaritalStatus(myfirstmodule.proxies.MaritalStatus maritalstatus)
	{
		setMaritalStatus(getContext(), maritalstatus);
	}

	/**
	 * Set value of MaritalStatus
	 * @param context
	 * @param maritalstatus
	 */
	public final void setMaritalStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.MaritalStatus maritalstatus)
	{
		if (maritalstatus != null) {
			getMendixObject().setValue(context, MemberNames.MaritalStatus.toString(), maritalstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MaritalStatus.toString(), null);
		}
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of AnnualSalary
	 */
	public final java.math.BigDecimal getAnnualSalary()
	{
		return getAnnualSalary(getContext());
	}

	/**
	 * @param context
	 * @return value of AnnualSalary
	 */
	public final java.math.BigDecimal getAnnualSalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AnnualSalary.toString());
	}

	/**
	 * Set value of AnnualSalary
	 * @param annualsalary
	 */
	public final void setAnnualSalary(java.math.BigDecimal annualsalary)
	{
		setAnnualSalary(getContext(), annualsalary);
	}

	/**
	 * Set value of AnnualSalary
	 * @param context
	 * @param annualsalary
	 */
	public final void setAnnualSalary(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal annualsalary)
	{
		getMendixObject().setValue(context, MemberNames.AnnualSalary.toString(), annualsalary);
	}

	/**
	 * @return value of SalesOrderQuantity
	 */
	public final java.lang.Integer getSalesOrderQuantity()
	{
		return getSalesOrderQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrderQuantity
	 */
	public final java.lang.Integer getSalesOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SalesOrderQuantity.toString());
	}

	/**
	 * Set value of SalesOrderQuantity
	 * @param salesorderquantity
	 */
	public final void setSalesOrderQuantity(java.lang.Integer salesorderquantity)
	{
		setSalesOrderQuantity(getContext(), salesorderquantity);
	}

	/**
	 * Set value of SalesOrderQuantity
	 * @param context
	 * @param salesorderquantity
	 */
	public final void setSalesOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer salesorderquantity)
	{
		getMendixObject().setValue(context, MemberNames.SalesOrderQuantity.toString(), salesorderquantity);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Customers that = (myfirstmodule.proxies.Customers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
